### ISSUE TITLE
Door unresponsive after members area crash

### ISSUE THREAD

**Issue by brackendawson** [somakeit/door-controller2#28]
Apparently the red LED was stuck on.

syslog content around issue:

```
Nov 15 19:52:04 kong doord.py[28808]: Found tag UID: ████████
Nov 15 19:52:04 kong doord.py[28808]: Tag is assigned to user ██████ (████ ████████)
Nov 15 19:52:04 kong doord.py[28808]: Tag ████████ authenticated
Nov 15 19:53:05 kong doord.py[28808]: Server returned bad status to POST:504 (send_queue: 3)
Nov 15 19:57:50 kong doord.py[28808]: Process Process-4120:
Nov 15 19:57:50 kong doord.py[28808]: Traceback (most recent call last):
Nov 15 19:57:50 kong doord.py[28808]: File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Nov 15 19:57:50 kong doord.py[28808]: self.run()
Nov 15 19:57:50 kong doord.py[28808]: File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
Nov 15 19:57:50 kong doord.py[28808]: self._target(*self._args, **self._kwargs)
Nov 15 19:57:50 kong doord.py[28808]: File "/opt/somakeit/door-controller2/doord.py", line 755, in _server_poll_worker
Nov 15 19:57:50 kong doord.py[28808]: self.local.update(json.loads(response.text))
Nov 15 19:57:50 kong doord.py[28808]: File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
Nov 15 19:57:50 kong doord.py[28808]: return _default_decoder.decode(s)
Nov 15 19:57:50 kong doord.py[28808]: File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
Nov 15 19:57:50 kong doord.py[28808]: obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Nov 15 19:57:50 kong doord.py[28808]: File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
Nov 15 19:57:50 kong doord.py[28808]: raise ValueError("No JSON object could be decoded")
Nov 15 19:57:50 kong doord.py[28808]: ValueError: No JSON object could be decoded
Nov 15 20:02:27 kong doord.py[28808]: Found tag UID: ████████
Nov 15 20:02:27 kong doord.py[28808]: Tag is assigned to user ██████ (██████ █████████)
Nov 15 20:02:27 kong doord.py[28808]: Tag ████████ authenticated
Nov 15 20:02:27 kong doord.py[28808]: Server poll still in progress, not starting another.
Nov 15 20:17:01 kong CRON[7743]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Nov 15 20:17:01 kong CRON[7736]: (CRON) info (No MTA installed, discarding output)
Nov 15 20:55:13 kong systemd[1]: Stopping Door Controller...
Nov 15 20:55:13 kong systemd[1]: Starting Door Controller...
Nov 15 20:55:13 kong systemd[1]: Started Door Controller.

```

**Comment by brackendawson** [comment]
I think the exception is unrelated, looks like it more likely crashed without output.

**Comment by Yommy** [comment]
It was my tag being used at 19:57 . Led stayed lit

**Comment by brackendawson** [comment]
Not going to fix this as the code is no longer used.
